name: Run TerraGrunt

on:
  workflow_dispatch: 
  push:
    branches:
      - 'production'
      - 'test'

env:
  CLOUD_ACCOUNT: aws-012901486517

jobs:
  run-terragrunt:
    name: terragrunt
    #runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            ref: ${{ env.GITHUB_REF_NAME }}

      - name: Fill variables
        run: |
            if [[ ${{ env.GITHUB_REF_NAME == 'production' }} ]]; then
              TG_PROJECT_PATH=${CLOUD_ACCOUNT}/production
            elif [[ ${{ env.GITHUB_REF_NAME == 'test' }} ]]; then
              TG_PROJECT_PATH=${CLOUD_ACCOUNT}/production
            fi
            echo "TG_PROJECT_PATH=${TG_PROJECT_PATH}" >> $GITHUB_ENV

      - name: Run Terragrunt
        run: |
          cd ${TG_PROJECT_PATH}
          terragrunt run-all plan --terragrunt-non-interactive
